# Paths to book files
my_book: "goi5.1.bin"
opp_book: "dec2015_500k.bin"

# Path to engine file
engine: "sf_latest"

# Whether or not to use preset lines for focused practice
use_lines: true

# Preset lines from which to start practicing
lines:
  - $hyperaccelerated e4 c5 Nf3 g6 [b]
  - neo-moller [b]
  - najdorf [wb]
  - sveshnikov [wb]
  - ruy lopez [wb]
  - benko gambit [wb]
  - scandinavian [w]
# Practice refuting dubious lines
  # - traxler [w]
  # - latvian gambit [w]
  # - marshall gambit [b]
  # - englund gambit [w]
  # - stafford gambit [w]
  # - falkbeer countergambit [w]
  # - philidor countergambit [w]
  # - winawer countergambit [w]
  # - danish gambit [b]
  # - blackmar diemer gambit [b]
  # - albin countergambit [wb]
  # - smith-morra gambit [b]
  # - von hennig schara gambit [w]
  # - four pawns [b]
